### ISSUE TITLE
Feature: Adjustable playing distance for SFX

### ISSUE THREAD

**Issue by L-22** [MineDragonCZ/Aunis#134]
If you build a base that involves the Stargate being placed several blocks away from a dialing computer, the sound effects of the gate cannot be heard.

A setting to change the playable distance of the SFX would be nice.

Thank you for reading.

**Comment by MineDragonCZ** [comment]
Hello, this "issue" is very common, and the main problem is, that we dont know how to fix this... I think that this is a problem of minecraft. Anyway, after we done the main things, this is first thing that we are going to do :)
