### ISSUE TITLE
Chevron didn't lit when incoming whormhole

### ISSUE THREAD

**Issue by Eclipsser** [MineDragonCZ/Aunis#140]
![2022-04-21_11 15 25](https://user-images.githubusercontent.com/66420124/164426340-96d4161c-bf39-4464-b0cd-cb58efdb8e92.png)

I dial with a dhd to this gate to the 6th chevron, then i canceled the dialing sequence, and i restarted it and completed, but the arrival gate didn't lit any chevron

Mods used : 
+ the 1.12 pack from technic launcher (modlist : https://www.technicpack.net/modpack/the-1122-pack.1406454/mods)
+ aunis v4.9.4.2

**Comment by MineDragonCZ** [comment]
Fixed in dev
