### ISSUE TITLE
Bug: Incoming whormhole without animation

### ISSUE THREAD

**Issue by Eclipsser** [MineDragonCZ/Aunis#146]
**Describe the bug**
Arrival gate without chevron lit or any incoming animation, just kawoosh and vortex

**To Reproduce**
1. Dial first 5 symbols with dhd
2. Dial the 6th one with a computer
3. Dial the point of origin with dhd
4. Engage the gate and see error

**Expected behavior**
At least lit chevrons, maybe an animation

**Screenshots**
![2022-04-29_23 49 19](https://user-images.githubusercontent.com/66420124/166073748-1d58b76b-493c-4ba9-8c86-23c7b4fbb84c.png)

**Mod version**
Version of mod you are using. (aunis-1.12.2-4.10.0.1)

**Comment by MineDragonCZ** [comment]
not fixed yet
