### ISSUE TITLE
2 Incoming Wormholes

### ISSUE THREAD

**Issue by Onyx1128** [MineDragonCZ/Aunis#148]
Describe the bug
When dialing a gate, if the other gates get a random incoming wormhole, the gate will still connect to the other.

To Reproduce:
Steps to reproduce behavior:
1.Dial the target gate, do not activate.
2.Execute a random incoming wormhole with a command or naturally.
3. Activate other gate before the random incoming wormhole gets established. Activate before 5th or 6th chevron lock.

Mod version
aunis-1.12.2-4.10.0.1

**Comment by MineDragonCZ** [comment]
Problem with RIG

**Comment by MineDragonCZ** [comment]
Fixed
