### ISSUE TITLE
Config Typo 

### ISSUE THREAD

**Issue by squall2044** [MineDragonCZ/Aunis#150]
Describe the bug:
Not sure if actually a bug but line 366 of the new config file says "# Do you want to spawn naquadah ores in the overworld?"

1. Install "aunis-1.12.2-4.10.0.1-client" and delete old config file if applicable.
2. Launch game to generate new config file
3. Open new config file
4. Scroll down to line 366

**Expected behavior**
The line to say "# Do you want to spawn titanium ores in the overworld?"

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/10217255/166110360-83c27594-999b-43eb-940f-b3c1a15ab136.png)

**Mod version**
aunis-1.12.2-4.10.0.1-client

**Additional context**
I am pretty sure 99.9% of people who use this mod will have no problems figuring it out from context but I wanted to let you know anyway.

**Comment by TheRedCreations** [comment]
Confirmed
