### ISSUE TITLE
Bug: Stargate Trinium iris breaks when it gets down to 50% durability

### ISSUE THREAD

**Issue by Powergate1** [MineDragonCZ/Aunis#154]
**Describe the bug**The Stargate Trinium iris breaks when it gets to 50% durabilty

**To Reproduce**
1. Go to a gate
2. Click on the gate
3. Input the Trinium iris and get the iris down to 500/1000 durability
4. Iris will break

**Expected behavior**
Trinium iris not to break

**Screenshots**

**Mod version**
aunis-1.12.2-4.10.0.1

**Additional context**

**Comment by TheRedCreations** [comment]
It's known. I reported it a while ago as tester. But Dragon didn't do something till now.
