### ISSUE TITLE
Feature: Debug Mode

### ISSUE THREAD

**Issue by TheRedCreations** [MineDragonCZ/Aunis#161]
**Is your feature request related to a problem? Please describe.**
When a game crash happens multiple times and CR doesn't say what happend.

**Describe the solution you'd like**
An Debug-Mode which prints much information Aunis does into the log.

**Comment by MineDragonCZ** [comment]
We have debug.log

**Comment by TheRedCreations** [comment]
Important things are missing: RIG, what mob spawned at rig, SG activated, SG deactivated, Ring activated, maybe Coords of these...

**Comment by MineDragonCZ** [comment]
Ok

**Comment by TheRedCreations** [comment]
Sweet. Ty
