### ISSUE TITLE
Gui Bug

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis#162]
**Creative menu that setups setting for specific stargate has bug and it only renders two settings**
![gui bug](https://user-images.githubusercontent.com/93074713/169861040-e3a4025a-4598-434f-9494-5fa85ffe897d.png)

**Comment by lukasz4444** [comment]
aunis version: **aunis-1.12.2-4.10.1.0-server.jar**

**Comment by lukasz4444** [comment]
@TheRedCreations it's not working
![no](https://user-images.githubusercontent.com/93074713/169863987-7152e34a-5edf-40d3-80da-89e60e51481d.png)

**Comment by Fredyman95** [comment]
And also it will never works because you have saved items/ blocks (Stargate blocks on left side on that picture)... So take out those blocks/items by point it and press A....


So read next time carefully....

**Comment by lukasz4444** [comment]
how to  scroll down there is no scrollbar

**Comment by lukasz4444** [comment]
nevermind
