### ISSUE TITLE
Bug: DHD chevron bug.

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis#166]
**Describe the bug**
Dialing invalid address with the dhd makes final chevron lock even if address is invalid.

**To Reproduce**
Dial any invalid stargate address in milky way on the dhd.

**Expected behavior**
Chevron with the point of the origin should not lock if address is invalid but it locks even with invalid adress.

**Mod version**
aunis-1.12.2-4.10.1.0

**Comment by MineDragonCZ** [comment]
WTF???

**Comment by MR-Spagetty** [comment]
what lukasz is saying is that in the show when a connection could not be established teh top chevron of teh gate does not lock whereas in teh mod even if a connection cannot be established the top chevron still locks as if a connection can be established

**Comment by MineDragonCZ** [comment]
> what lukasz is saying is that in the show when a connection could not be established teh top chevron of teh gate does not lock whereas in teh mod even if a connection cannot be established the top chevron still locks as if a connection can be established

But only if u dialing with computer (in SGC)

**Comment by TheRedCreations** [comment]
By dialling with DHD you know the answer of the other gate when you push the BRB.

**Comment by MR-Spagetty** [comment]
> > what lukasz is saying is that in the show when a connection could not be established teh top chevron of teh gate does not lock whereas in teh mod even if a connection cannot be established the top chevron still locks as if a connection can be established
> 
> But only if u dialing with computer (in SGC)

no, it also occurred in the show when using a DHD (also in teh show teh chevron didnt move when using teh dhd it just didnt light up when a connection couldn't be established)
